import Layout from 'src/layout/layout'
import { Button } from '@mui/material'
import Head from 'next/head'


export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <Button>Click</Button>
    </Layout>
  )
}
